apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
  namespace: app
  labels:
    app: main-service
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service 
  template:
    metadata:
      labels:
        app: main-service 
    spec:
      containers:
      - name: main-service
        image: saloyiana/main-service
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: NodePort
  selector:
    app: main-service
  ports:
    - port: 80
      targetPort: 80
