apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jenkins
  namespace: jenkins
spec:
  chart: stable/jenkins
  targetNamespace: jenkins
  valuesContent: |-
    master:
      image: jenkinsci/blueocean
      tag: latest
      jenkinsUriPrefix: /jenkins
